package com.player2.playerengine.tasks.farming;

import java.util.Locale;

/** Shared bounded failure vocabulary for setup and harvest operations. */
public enum FarmTaskReason {
    NONE,
    ELLIEGPS_DISABLED,
    STORE_UNAVAILABLE,
    TYPE_CONFLICT,
    NO_SUITABLE_SITE,
    WATER_EVAPORATES,
    EXACT_SITE_UNSAFE_SUPPORT,
    EXACT_SITE_UNSAFE_OBSTRUCTION,
    EXACT_SITE_FLUID_CONFLICT,
    EXACT_SITE_CROP_CONFLICT,
    EXACT_SITE_REPAIR_LIMIT_EXCEEDED,
    EXACT_SITE_NO_SAFE_STANCE,
    EXACT_SITE_FREEZE_RISK,
    FREEZE_RISK,
    RESOURCE_TIMEOUT,
    RESOURCE_RETURN_FAILED,
    BUCKET_UNAVAILABLE,
    HOE_UNAVAILABLE,
    REPAIR_TOOL_UNAVAILABLE,
    DIRT_UNAVAILABLE,
    HOE_REACQUIRE_FAILED,
    WATER_SOURCE_NOT_FOUND,
    MANIFEST_DRIFT,
    INTERACTION_DENIED,
    WAYPOINT_JSON_FAILURE,
    FARM_NOT_FOUND,
    STALE_CENTER,
    SEARCH_SCAN_LIMIT,
    PARTIAL_DENIED,
    ALL_DENIED,
    SETUP_TIMEOUT,
    HARVEST_TIMEOUT,
    CHUNK_UNLOADED,
    DIMENSION_CHANGED,
    CANCELLED_OPERATOR,
    UNSUPPORTED_DATA,
    INTERNAL_CONTRACT_FAILURE;

    public String controlledReason() {
        return name().toLowerCase(Locale.ROOT);
    }
}
